apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: the-tip-top-front

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: joanisky/the-tip-top-front
    newName: joanisky/the-tip-top-front
    newTag: latest